version: '3.8'

services:

  # Zookeeper - Kafka needs this to coordinate brokers
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: intelliguard-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # Kafka broker - the actual message queue
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: intelliguard-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

  # Redis - already using this from Day 4
  redis:
    image: redis:7.2
    container_name: intelliguard-redis
    ports:
      - "6379:6379"

  # PostgreSQL - our main database
  postgres:
    image: postgres:16
    container_name: intelliguard-postgres
    environment:
      POSTGRES_DB: intelliguard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: